//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st_Mihailova_telecom1_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class st1_Mihailova_telecomEntities : DbContext
    {
        private static st1_Mihailova_telecomEntities baze;
        public st1_Mihailova_telecomEntities()
            : base("name=st1_Mihailova_telecomEntities")
        {
        }

        public static st1_Mihailova_telecomEntities getContext()
        {
            if (baze == null) { baze = new st1_Mihailova_telecomEntities(); }
            return baze;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
